### ISSUE TITLE
Resolve api call just return status and location

### ISSUE THREAD

**Issue by wmendes** [monbro/meteor-soundcloud-nodejs-api-wrapper-package#1]
Code:
var track = client.getSync('/resolve', {"url" : url, limit: 1});
console.log(track);

Return:
{ status: '302 - Found',
location: 'https://api.soundcloud.com/tracks/217485762?client_id=d3c2c19609906ce5a070191cf86980d5' }

**Comment by monbro** [comment]
Is this not what you are looking for and /resolve is proposed to do? The Status is 302 -> found. Let me know if otherwise.
